### ISSUE TITLE
Error in bfs_get_data

### ISSUE THREAD

**Issue by sachavarone** [lgnbhl/BFS#10]
Dear Félix,

I've just discovered this nice package. Thank you for providing it!

I came across an issue when running your example using the query parameter in `bfs_get_data`:
```
Error in query == "all" || is.null(query) : 
  'length = 4' in coercion to 'logical(1)'
```

The following change inside the `bfs_get_data` definition might solve this issue:
```
if (any(query == "all" | is.null(query))) {
```
instead of
```
if (any(query == "all" || is.null(query))) {
```

Best regards,
Sacha

**Comment by lgnbhl** [comment]
Dear Sacha,

Thank you very much for your message and sharing this error.

I tested your fix but it seems it doesn't work on the examples provided by the README.md (https://github.com/lgnbhl/BFS/commit/59b07e2270bfe2e55de5154c329b715663a06c67). As a solution I removed the logic to use only the NULL argument:

```r
if (is.null(query)) {
```

This changed as been pushed to GitHub (https://github.com/lgnbhl/BFS/commit/63e87e8b7304f92f779169cb17e067a8b8cc06e6).

Could you please reinstall BFS with `devtools::install_github("lgnbhl/BFS")` (BFS 0.5.1) and tell me if you still have this error. If not, feel free to close this issue. 

For the record, before the default was `bfs_get_data(..., query = "all")` but since v.0.4.8 the default is `bfs_get_data(..., query = NULL)`. The logic you mentionned was implemented to avoid a breaking change.

This change is in BFS version 0.5.1, currently pending for manual inspection by a CRAN team member. 

Best regards,
Félix
